[project]
name = "reading-list"
version = "0.1.0"
description = "Reading List Generator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bibtexparser>=1.4.3",
    "pylatexenc>=2.10",
]
